# Generated by Django 5.1.6 on 2025-02-13 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('rate per kg', 'Rate per kg')], max_length=50)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10)),
                ('fat_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10)),
                ('collection_date', models.DateField()),
                ('measured', models.CharField(choices=[('liters', 'Liters'), ('kg', 'Kg')], max_length=10)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('snf_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.customer')),
                ('fat_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat_rates', to='collector.ratechart')),
                ('snf_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snf_rates', to='collector.ratechart')),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
